language: elixir

elixir:
  - 1.2.3
otp_release:
  - 18.2.1

env:
  - EVENT_STORE_VERSION='14.04-v3.5.0'

before_install:
  - wget http://download.geteventstore.com/binaries/EventStore-OSS-Ubuntu-${EVENT_STORE_VERSION}.tar.gz
  - tar xf EventStore*.tar.gz
  - cd EventStore* && ./run-node.sh --mem-db 2>&1> eventstore.log &
  - /bin/sleep 3

after_scripts:
  - killall -SIGINT clusternode
  - cat EventStore*/eventstore.log
